name: Podcast Auto Puller

on:
  schedule:
    # Run every 6 hours (0, 6, 12, 18 UTC)
    - cron: '0 */6 * * *'
  workflow_dispatch: # Allow manual trigger from GitHub UI

jobs:
  pull-episodes:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Run podcast puller
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          MAX_EPISODES_PER_RUN: "3"  # Pull up to 3 episodes per run
        run: |
          echo "🤖 Starting automated podcast pull..."
          echo "⏰ Current time: $(date)"
          python -m src.main
          echo "✅ Podcast pull completed"
      
      - name: Notify on failure
        if: failure()
        run: |
          echo "❌ Podcast puller failed!"
          echo "Check the logs above for details"
